-- ============================================================
-- PostgreSQL Schema for interview-guide
-- 对比 H2 vs PostgreSQL 数据类型差异
-- ============================================================
-- 注意：JPA 的 ddl-auto: update 会自动建表，此文件仅用于：
--   1. 学习 PostgreSQL DDL 语法
--   2. 理解 H2 与 PostgreSQL 的类型差异
--   3. 需要手动管理 schema 时使用
-- ============================================================

-- 聊天会话表
CREATE TABLE IF NOT EXISTS chat_sessions (
    id           BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- H2: BIGINT AUTO_INCREMENT
    -- PG: BIGINT GENERATED BY DEFAULT AS IDENTITY (SQL 标准)
    --   ↑ PG 也支持 SERIAL，但 IDENTITY 是标准写法，JPA 默认生成它

    session_id   VARCHAR(36)  NOT NULL UNIQUE,
    created_at   TIMESTAMP    NOT NULL DEFAULT NOW()
    -- H2: TIMESTAMP
    -- PG: TIMESTAMP (无时区)
    --   ↑ 两者行为一致
);

-- 聊天消息表
CREATE TABLE IF NOT EXISTS chat_messages (
    id           BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   VARCHAR(36)  NOT NULL,
    role         VARCHAR(16)  NOT NULL,
    -- role: 'user' | 'assistant' | 'system'
    content      TEXT         NOT NULL,
    -- H2: TEXT → java.lang.String (无限)
    -- PG: TEXT → 无限长度，与 H2 兼容

    created_at   TIMESTAMP    NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_message_session_id ON chat_messages(session_id);

-- 面试会话表
CREATE TYPE session_status AS ENUM ('CREATED', 'IN_PROGRESS', 'COMPLETED', 'EVALUATED');
-- H2: 支持 CREATE TYPE ... AS ENUM
-- PG: 原生支持 ENUM，语义一致
-- 如果用 JPA EnumType.STRING → 也可用 VARCHAR(20) 替代 ENUM

CREATE TABLE IF NOT EXISTS interview_sessions (
    id                      BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id              VARCHAR(36)  NOT NULL UNIQUE,
    skill_id                VARCHAR(100) NOT NULL,
    difficulty              VARCHAR(20)  NOT NULL,
    status                  VARCHAR(20)  NOT NULL DEFAULT 'CREATED',
    -- JPA 用 EnumType.STRING → 存 "CREATED" 等字符串
    -- 如果用 EnumType.ORDINAL → 存 0,1,2,3（不推荐，易乱）

    current_question_index  INT       NOT NULL DEFAULT 0,
    questions_json          TEXT,
    -- questions_json: 题目列表存为 JSON 字符串
    -- H2: TEXT / PG: TEXT — 类型兼容

    overall_score           INT,
    overall_feedback        TEXT,
    report_json             TEXT,

    created_at              TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 面试答案表
CREATE TABLE IF NOT EXISTS interview_answers (
    id                BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id        VARCHAR(36)  NOT NULL,
    question_index    INT          NOT NULL,
    question          TEXT         NOT NULL,
    question_category VARCHAR(255) NOT NULL,
    user_answer       TEXT         NOT NULL,
    score             INT          NOT NULL DEFAULT 0,
    feedback          TEXT,
    correct_answer    TEXT,
    created_at        TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- ============================================================
-- H2 → PostgreSQL 关键差异总结
-- ============================================================
-- 1. 自增主键
--    H2: BIGINT AUTO_INCREMENT
--    PG: BIGINT GENERATED BY DEFAULT AS IDENTITY  (或 BIGSERIAL)
--    → JPA 的 GenerationType.IDENTITY 自动适配，无需修改代码
--
-- 2. TEXT 类型
--    H2: TEXT = java.sql.Types.CLOB（最大 256MB）
--    PG: TEXT = 无长度限制（~1GB）
--    → 兼容，columnDefinition = "TEXT" 在两者上都能用
--
-- 3. VARCHAR(n)
--    H2: 字符数（UTF-16），中英文都算 1 个
--    PG: 字符数（UTF-8），中英文都算 1 个
--    → 语义一致
--
-- 4. 索引
--    H2: CREATE INDEX idx ON table(col)
--    PG: 同上，标准 SQL
--    → 通用
--
-- 5. BOOLEAN
--    H2: BOOLEAN 映射为 TINYINT(1)
--    PG: BOOLEAN 原生 true/false
--    → JPA boolean 字段自动适配
--
-- 6. 序列
--    H2: 表级自增，无独立序列对象
--    PG: 独立 SEQUENCE 对象，支持更细粒度控制
--    → 生产环境 PG 可用 @SequenceGenerator 优化批量插入性能
-- ============================================================
